### ISSUE TITLE
General principle of verifier queries?

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/beacon-verifier#4]
All - I may not have gotten the principle of the verifier queries:

* most endpoints (except `info`, `map` ...) will respond with an error when not being queried with a valid query (in contrast to a query with a non-match)
* ... therefore, the verifier can only test error responses

Proposal:

* require a correct true and possibly false query for each endpoint

**Comment by mbaudis** [comment]
@MrRobb @jrambla Can you please provide example definitions and responses which would validate? Could it be that there is the expectation that an endpoint such as `/analyses` returns **ALL** analyses? Which doesn't make a lot of sense, even with pagination IMO.

Solution: Valid example endpoints, which also can then used to populate example pages etc.

```
    biosample:
      entry_type: biosample
      root_url: https://progenetix.org/beacon/biosamples
      single_entry_url: https://progenetix.org/beacon/biosamples/___id___
      example_entry_urls:
        - http://progenetix.org/beacon/biosamples/pgxbs-kftva5c9
        - http://progenetix.org/beacon/biosamples/pgxbs-kftvgkj3
```

* http://progenetix.org/beacon/biosamples/pgxbs-kftva5c9
* http://progenetix.org/beacon/biosamples/pgxbs-kftvgkj3

Also: There is AFAIK no documentation about this - i.e. why the checks fail. But relying on "endpoint delivers all if not limited" is a very dangerous concept (server load & security wise). Yes, one can set the paging to a limited value & provide the document count + a single example, but this is IMO a hack.

So: Please re-think & then document what the standard behaviour should be.
